### ISSUE TITLE
Policies don't see to work - Also extra MinIO text

### ISSUE THREAD

**Issue by MantleFounder** [mantle-labs/console#17]
![image](https://user-images.githubusercontent.com/38961332/201633994-a2d22a29-0c9c-4539-bb54-356ca7bb8d4a.png)
![image](https://user-images.githubusercontent.com/38961332/201634242-de87a31c-d27e-49e2-893d-15d8e89cf7d7.png)

**Comment by ben-nole** [comment]
fixed in translate pr
